package com.Zanzibar.Public.Announcement.annoucement;

import jakarta.validation.constraints.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;
import java.time.LocalTime;

@Getter
@Setter
public class AnnouncementRequest {

    // =========================================================
    // TYPE
    // =========================================================

    @NotNull(message = "Announcement type is required")
    private AnnouncementType type;


    // =========================================================
    // APPLICANT INFORMATION
    // =========================================================

    @NotBlank(message = "Applicant name is required")
    @Size(
            max = 100,
            message = "Applicant name must not exceed 100 characters"
    )
    private String applicantName;

    @NotBlank(message = "Phone number is required")
    @Size(
            max = 20,
            message = "Phone number must not exceed 20 characters"
    )
    private String phoneNumber;


    // =========================================================
    // DEATH INFORMATION
    // =========================================================

    @Size(max = 150)
    private String deceasedName;

    @Size(max = 20)
    private String gender;

    @Min(value = 0, message = "Age cannot be negative")
    @Max(value = 150, message = "Age is invalid")
    private Integer age;

    private LocalDate dateOfDeath;

    @Size(max = 150)
    private String placeOfDeath;

    @Size(max = 150)
    private String burialPlace;

    private LocalDate burialDate;

    private LocalTime burialTime;

    private String familyMembers;

    @Size(max = 100)
    private String contactPerson;


    // =========================================================
    // LOST / FOUND
    // =========================================================

    @Size(max = 150)
    private String itemName;

    @Size(max = 100)
    private String itemCategory;

    private String description;

    @Size(max = 200)
    private String location;

    private LocalDate eventDate;

    @Size(max = 100)
    private String reward;


    // =========================================================
    // GENERAL
    // =========================================================

    private String additionalInformation;

    /**
     * Announcement text generated by the mobile app according to
     * the citizen's selected language (Swahili or English).
     *
     * The backend stores this exact text so the same language is
     * preserved for moderation, PDF generation, radio broadcasting
     * and public viewing.
     */
    private String generatedText;
}